name: umar_media
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  appinio_video_player: ^1.3.0
  badges: ^3.1.2
  circular_reveal_animation: ^2.0.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.2.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.1.2
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
